POST http://localhost:3001/api/habits
 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRlZXBjIiwiaWQiOiI2NWQzZDJiN2Q1ZmU3ZTc5ODQ5Y2Y5MDMiLCJpYXQiOjE3MDg0NTQ1OTZ9.bHddiYGuFJo3PdhTR_nN3_EBjVODqxLexBBMXNAXFw4
{ 
    "title": "xyz",
    "desciption": "xyz",
    "category": "xyz",
    "frequency": "xyz",
    "target": "xyz",
    "startDate": "xyz",
    "endDate": "xyz",
    "logs": "xyz"
}